/* CALLS TABLE HAS THREE COLS NAMELY FROM_ID,TO_ID AND DURATION .
WAQ TO REPORT THE NUMBBER OF CALLS AND THE TOTAL CALL DURATION BETWEEN EACH PAIR OF DISTINCT PERSONS
WHERE PERSON 1 IS LESS THAN PERSON 2*/

DROP TABLE IF EXISTS  CALLS
CREATE TABLE CALLS
(
FROM_ID INT
,TO_ID INT
,DURATION INT
)

INSERT INTO CALLS
SELECT 1,2,59
UNION ALL
SELECT 2,1,11
UNION ALL  
SELECT 1,3,20
UNION ALL  
SELECT 3,4,100
UNION ALL  
SELECT 3,4,200
UNION ALL  
SELECT 3,4,200
UNION ALL  
SELECT 4,3,499

SELECT * FROM CALLS

;WITH CALLS_CTE AS
(
SELECT  case when from_id <to_id then from_id else to_id end as from_id
,case when to_id> from_id  then  to_id else from_id end as to_id,DURATION
FROM CALLS 
)

SELECT from_id,to_id
,count(1)as [CALL_COUNT],sum(DURATION) as [Total Duration]
FROM CALLS_CTE
GROUP BY from_id,to_id

