-- WAQ TO DERIVE THE START AND END DATES FOR EACH STATE OF TASK
DROP table IF EXISTS tasks
create table tasks (
date_value date,
state varchar(10)
);

insert into tasks  values ('2019-01-01','success'),('2019-01-02','success'),('2019-01-03','success'),('2019-01-04','fail')
,('2019-01-05','fail'),('2019-01-06','success')

SELECT * FROM tasks


;WITH FIRSTCTE AS (
SELECT date_value,STATE,ROW_NUMBER() OVER (PARTITION BY STATE ORDER BY DATE_VALUE) AS RN
FROM TASKS
)
,SECONDCTE AS(
SELECT *
,DATEADD(DAY,-RN,DATE_VALUE) AS ORIGINALdATE FROM FIRSTCTE)

--- THE CONSECUTIVE DATE VALUES WILL HAVE SAME ORIGINAL DATE

SELECT STATE,MIN(DATE_VALUE) AS STARTDATE,MAX(DATE_VALUE) AS ENDDATE
FROM SECONDCTE
GROUP BY STATE,ORIGINALDATE
ORDER BY MIN(DATE_VALUE)

