--Convert data from Rows to Columns 

DROP TABLE IF EXISTS EMP

CREATE TABLE EMP
(NAME VARCHAR(50),
VALUE VARCHAR(50),
ID INT);

INSERT INTO EMP VALUES ('NAME','CHARAN',1),('GENDER','MALE',1),('SALARY','90000',1)

SELECT * FROM EMP

--METHOD 1: USING CASE STATEMENT

SELECT ID,
MAX(CASE WHEN NAME='NAME' THEN VALUE ELSE '' END) AS NAME,
MAX(CASE WHEN NAME='GENDER' THEN VALUE ELSE '' END) AS GENDER,
MAX(CASE WHEN NAME='SALARY' THEN VALUE ELSE ''  END) AS SALARY
FROM EMP
GROUP BY ID


--METHOD 2: USING PIVOT
SELECT ID,[NAME],[GENDER],[SALARY]
FROM 
(
SELECT ID,NAME AS ENAME,VALUE
FROM EMP
) AS SOURCE_TBL
PIVOT (MAX(VALUE)
FOR ENAME IN ([NAME],[GENDER],[SALARY])
) AS PVT_TBL

