DROP TABLE IF EXISTS STORES
CREATE TABLE STORES (
Store varchar(10),
Quarter varchar(10),
Amount int);

INSERT INTO STORES (Store, Quarter, Amount)
VALUES ('S1', 'Q1', 200),
('S1', 'Q2', 300),
('S1', 'Q4', 400),
('S2', 'Q1', 500),
('S2', 'Q3', 600),
('S2', 'Q4', 700),
('S3', 'Q1', 800),
('S3', 'Q2', 750),
('S3', 'Q3', 900);

SELECT * FROM STORES

SELECT 1+2+3+4
--Method 1 Aggregation

SELECT STORE,CONCAT('Q',10-SUM(CAST(RIGHT(QUARTER,1) AS INT)))  AS MISSING_QUARTER
FROM STORES
GROUP BY STORE

--Method 2 Recursive CTE

;WITH RCTE AS
(SELECT DISTINCT STORE,1 AS QUARTER FROM STORES
UNION ALL
SELECT  STORE,QUARTER+1 AS QUARTER FROM RCTE
WHERE QUARTER<4
)
SELECT STORE ,CONCAT('Q',QUARTER) AS MISSINGQUARTER 
FROM RCTE
EXCEPT 
SELECT STORE,QUARTER FROM STORES

--Method 3 CROSS JOIN
;WITH CJ_CTE AS
(SELECT DISTINCT S1.STORE,S2.QUARTER 
FROM STORES S1,STORES S2
)
SELECT STORE ,QUARTER AS MISSINGQUARTER 
FROM CJ_CTE
EXCEPT 
SELECT STORE,QUARTER FROM STORES
