DROP TABLE IF EXISTS HOLIDAY_LIST
CREATE TABLE HOLIDAY_LIST
( MONTH NVARCHAR(10)
,DAY INT
,DATE_OF_MONTH DATE
)



INSERT INTO HOLIDAY_LIST(MONTH,DAY,DATE_OF_MONTH)
SELECT 'JAN',31,'2022-01-31'
UNION ALL
SELECT 'FEB',28,'2022-02-28'
UNION ALL
SELECT 'MAR',31,'2022-03-31'

SELECT * FROM HOLIDAY_LIST


DECLARE @EndofMonth DATE=EOMONTH(GETDATE(),-6)
,@LastWorkingDay  DATE;

SELECT @LastWorkingDay=CASE WHEN DATEPART(DW,@EndofMonth)=1 THEN DATEADD(DAY,-2,@EndofMonth)
WHEN DATEPART(DW,@EndofMonth)=7 THEN DATEADD(DAY,-1,@EndofMonth)
ELSE @EndofMonth
END 


SELECT @LastWorkingDay

WHILE EXISTS (SELECT 1 FROM HOLIDAY_LIST WHERE DATE_OF_MONTH=@LastWorkingDay)
BEGIN 


SET @LastWorkingDay=DATEADD(DAY,-1,@LastWorkingDay)

END 

SELECT CASE WHEN DATEPART(DW,@LastWorkingDay)=1 THEN DATEADD(DAY,-2,@LastWorkingDay)
WHEN DATEPART(DW,@LastWorkingDay)=7 THEN DATEADD(DAY,-1,@LastWorkingDay)
ELSE @LastWorkingDay END AS LWD

