/*
WAQ TO FIND THE NTH OCCURANCE OF SUNDAY FROM A GIVEN DAY
SUNDAY=1
MONDAY=2
:
:
SATURDAY=7
*/

SELECT DATENAME(WEEKDAY,'2022-01-02')--SUNDAY

SELECT DATENAME(WEEKDAY,'2022-01-01')--SATURDAY

DECLARE @TODAY DATE='2022-01-01'
,@N INT =3-- TO STATE THE OCCURANCE (3RD SUNDAY)

SELECT DATEADD(DAY,8-DATEPART(WEEKDAY,@TODAY),@TODAY) --FINDS THE 1ST SUNDAY

SELECT DATEADD(WEEK,@N-1,DATEADD(DAY,8-DATEPART(WEEKDAY,@TODAY),@TODAY) )-- FINDS THE NTH SUNDAY

--TO FIND THE 4 TH MONDAY
DECLARE @TODAY DATE='2022-04-02'
,@N INT =4-- TO STATE THE OCCURANCE (3RD SUNDAY)

SELECT DATEADD(DAY,9-DATEPART(WEEKDAY,@TODAY),@TODAY) --FINDS THE 1ST MONDAY

SELECT DATEADD(WEEK,@N-1,DATEADD(DAY,9-DATEPART(WEEKDAY,@TODAY),@TODAY) )-- FINDS THE NTH MONDAY