DROP TABLE  IF EXISTS SALES
CREATE TABLE SALES (
PRODUCT_ID INT,
PERIOD_START DATE,
PERIOD_END DATE,
AVERAGE_DAILY_SALES INT
);

INSERT INTO SALES VALUES(1,'2019-01-25','2019-02-28',100),(2,'2018-12-01','2020-01-01',10),(3,'2019-12-01','2020-01-31',1);

GO

SELECT * FROM SALES

;WITH REC_CTE AS (

SELECT PRODUCT_ID,PERIOD_START,PERIOD_END,AVERAGE_DAILY_SALES
FROM SALES
UNION ALL
SELECT PRODUCT_ID,DATEADD(DAY,1,PERIOD_START) AS PERIOD_START,PERIOD_END,AVERAGE_DAILY_SALES
FROM REC_CTE
WHERE PERIOD_START<PERIOD_END
 
)

SELECT PRODUCT_ID,YEAR(PERIOD_START) AS REPORTYEAR,SUM(AVERAGE_DAILY_SALES) AS TOTALSALES
FROM REC_CTE
GROUP BY PRODUCT_ID,YEAR(PERIOD_START)
ORDER BY PRODUCT_ID,YEAR(PERIOD_START)
OPTION (MAXRECURSION 1000);