DROP TABLE IF EXISTS ACTIVITY

CREATE table activity
(
user_id varchar(20),
event_name varchar(20),
event_date date,
country varchar(20)
);

insert into activity values (1,'app-installed','2022-01-01','India')
,(1,'app-purchase','2022-01-02','India')
,(2,'app-installed','2022-01-01','USA')
,(3,'app-installed','2022-01-01','USA')
,(3,'app-purchase','2022-01-03','USA')
,(4,'app-installed','2022-01-03','India')
,(4,'app-purchase','2022-01-03','India')
,(5,'app-installed','2022-01-03','SL')
,(5,'app-purchase','2022-01-03','SL')
,(6,'app-installed','2022-01-04','Pakistan')
,(6,'app-purchase','2022-01-04','Pakistan');


SELECT * FROM activity ORDER BY USER_ID

-- ACTIVE USER COUNT AT DAILY LEVEL

SELECT EVENT_DATE,COUNT(DISTINCT USER_ID) AS ACTIVEUSERCOUNT
FROM ACTIVITY
GROUP BY EVENT_DATE



-- ACTIVE USER COUNT AT WEEKLY LEVEL

SELECT *,DATEPART(WEEK,EVENT_DATE) FROM activity

SELECT DATEPART(WEEK,EVENT_DATE) AS WEEK,COUNT(DISTINCT USER_ID) AS ACTIVEUSERCOUNT
FROM ACTIVITY
GROUP BY DATEPART(WEEK,EVENT_DATE)

--DATEWISE TOTAL NO OF USERS WHO PURCHASED THE SAME DAY AS THEY INSTALLED THE APP

;WITH USERACTIVITIES AS 
(
SELECT USER_ID,EVENT_DATE,COUNT(DISTINCT EVENT_NAME) AS DISTINCTACTIVITES
FROM ACTIVITY
GROUP BY USER_ID,EVENT_DATE
)

SELECT event_date,SUM(CASE WHEN DISTINCTACTIVITES=2 THEN 1 ELSE 0 END) AS PURCHASEDSAMEDAYCOUNT
FROM USERACTIVITIES
GROUP BY event_date

-- PERCENTAGE  OF PAID USERS INDIA ,USA AND OTHER

SELECT * FROM ACTIVITY WHERE event_name='app-purchase'
;WITH COUNTRY_WISE_PAIDUSERS AS
(
SELECT CASE WHEN COUNTRY IN ('INDIA','USA') THEN COUNTRY ELSE 'OTHER' END AS COUNTRY 
,COUNT(DISTINCT USER_ID) AS PAIDUSERCOUNT
FROM ACTIVITY
WHERE event_name='app-purchase'
GROUP BY CASE WHEN COUNTRY IN ('INDIA','USA') THEN COUNTRY ELSE 'OTHER' END
)

SELECT COUNTRY
,100.0*PAIDUSERCOUNT/(SELECT SUM(PAIDUSERCOUNT) FROM COUNTRY_WISE_PAIDUSERS) AS [%OFPAIDUSERS]
FROM COUNTRY_WISE_PAIDUSERS

SELECT *FROM ACTIVITY

--OUT OF USERS WHO INSTALLED THE APP HOW MANY PURCHASED THE SUBSCRIPTION THE VERY NEXTDAY (DAILY LEVEL COUNT)

/*
2022-01-01 0
2022-01-02 1
2022-01-03 0
2022-01-04 0
*/
;WITH USERDATA AS
(SELECT *,LAG(EVENT_NAME,1) OVER(PARTITION BY USER_ID ORDER BY EVENT_DATE ) AS PREVACTIVITY
,LAG(EVENT_DATE,1) OVER(PARTITION BY USER_ID ORDER BY EVENT_DATE ) AS PREVEVENTDATE
FROM ACTIVITY
)


SELECT EVENT_DATE,
SUM(CASE WHEN event_name='app-purchase' AND PREVACTIVITY='app-installed' 
AND DATEDIFF(DAY,PREVEVENTDATE,EVENT_DATE)=1 THEN 1 ELSE 0 END) AS NEXTDAYPURCHASECOUNT
FROM USERDATA
GROUP BY EVENT_DATE

--SELECT EVENT_DATE,COUNT(DISTINCT USER_ID) AS CNT
--FROM USERDATA
--WHERE event_name='app-purchase' AND PREVACTIVITY='app-installed' 
--AND DATEDIFF(DAY,PREVEVENTDATE,EVENT_DATE)=1
--GROUP BY EVENT_DATE

